### ISSUE TITLE
Remove `redis` driver

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-file-server#46]
https://github.com/flowforge/flowforge-file-server/blob/0a6470e451f4aa3bed0e436c63e1ffaa4d75e5c0/README.md?plain=1#L160

Given we do not use this driver ourselves we should remove the `redis` driver from the repo.

We'll have it in the git history if we ever need to reconsider it.

**Comment by hardillb** [comment]
closed by #48
